name: ATCH Stock AI Auto Update

on:
  schedule:
    - cron: "30 22 * * 1-5"

  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-stock:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy pandas yfinance scikit-learn joblib tensorflow

      - name: Run ATCH AI prediction
        run: |
          python update_stock.py

      - name: Check changes
        run: |
          git status

      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add data/

          git diff --cached --quiet || \
            git commit -m "Auto update ATCH stock data"

          git push
